[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pyhardgen"
version = "0.2.0"
authors = [
  { name="Gabriel Martinz", email="gabriel.martinz@ga.ita.br" },
]
readme = "README.md"
requires-python = ">=3.10"