name: "exp1"
ngpu: 1
workers: 2
runs: 2
epochs: 20

nn:
  n_layers: 5 # number of hidden layers
  # number of features for each linear layer, for decoder this will be reversed
  # len must be equal to n_layers
  features: [256, 64, 16, 8, 4]
  activation: relu
  loss: cross_entropy
  dropout: 0.1

dataset:
  filename: sjc_internacao.csv
  batch_size: 256

optimizer:
  lr: 0.00001
  weight_decay: 0.0001